/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_letgo_common_MainActivity */

#ifndef _Included_com_yj_letgo_common_MainActivity
#define _Included_com_yj_letgo_common_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yj_letgo_common_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yj_letgo_common_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
